### ISSUE TITLE
Cannot delete files and documents

### ISSUE THREAD

**Issue by vincentbitter** [sismics/docs#539] opened 2021-05-23 19:27 UTC
**Issue:**
I cannot delete any files or documents anymore. 

**Reproduction steps:**
1. Run Teedy in a Docker image
2. Use Traefik as a reverse proxy (not sure if it has anything to do with it)
3. Login with a user
4. Go to a document and try to delete => Nothing seems to happen
5. Go to a file and try to delete => Nothing seems to happen

**Root cause**
In the network console, I am getting `Error 415 Unsupported Content Type` from Jetty in both Firefox and Chrome. 
If I change the `content-type` in the request headers from `text/plain` to `application/x-www-form-urlencoded`, it seems to work.
Might has something to do with adding `@Consumes(MediaType.APPLICATION_FORM_URLENCODED)` to the BaseResource class in https://github.com/sismics/docs/commit/6fcd8771a5e15cd16b8b4f35ae01520eb0c87865

**Comment by jendib** [comment] 2021-05-27 10:37
I cannot reproduce on https://demo.teedy.io/ running 1.9

**Comment by vincentbitter** [comment] 2021-05-27 11:45
I am running 1.10, but will try to downgrade

**Comment by jendib** [comment] 2021-05-27 11:51
I didn't notice that the commit you mentioned is actually not in 1.9.
I wait for your downgrade to confirm that it's coming from there. Thanks

**Comment by vincentbitter** [comment] 2021-05-30 11:46
Thanks for reopening this issue! I downgraded my Docker container from jdreinhardt/teedy:latest (v1.10) to jdreinhardt/teedy:1.9 and this solved the issue.

**Comment by jendib** [comment] 2022-01-02 15:50
Fixed in v1.10

**Closed by jendib** 2022-01-02 15:50 UTC
Labels: bug
