### ISSUE TITLE
Feature Request: Document Expiration

### ISSUE THREAD

**Issue by serelsnauw** [sismics/docs#594] opened 2021-12-08 08:55 UTC
Hi,

First of all, thank you for your'e awesome application. It works great, is easy to use, and looks perfect!

For full usage would it be nice to have a feature for some kind of document expiration. 
Some business-policies require a form of revision after X years. When adding (or publishing) a new document would be nice option to add a expiration-date. When the date expires, it would be nice to receive some kind of notification (or trigger a workflow) for this document.

Again, thank you guys!
Grtz Serel.

**Comment by jendib** [comment] 2022-01-02 16:03
Duplicate of #191

**Closed by jendib** 2022-01-02 16:03 UTC
