### ISSUE TITLE
Prevent duplicate tag creation

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#298] opened 2019-02-11 13:58 UTC
Hi,
i just recognized that tags can be created multiple times. I created one accidently
![grafik](https://user-images.githubusercontent.com/5631071/52567761-5494c800-2e0d-11e9-8477-8eeb4e553390.png)

I think this should be forbidden to grant proper longterm meta data population

best regards, Mario

**Comment by jendib** [comment] 2019-02-11 14:02
I'm aware of this, but the issue is more complicated than expected, expecially about how to handle the unicity.
Duplicate of #197.

**Closed by jendib** 2019-02-11 14:02 UTC
