### ISSUE TITLE
Enhancement request: Inherit permissions on tags

### ISSUE THREAD

**Issue by Craneson** [sismics/docs#626] opened 2022-03-20 19:14 UTC
I would appreciate an option for tags, to switch between explicit permissions and inheriting the parent-permissions.

An idea would be to take the windows-approach for file-permissions: by default each sub-tag inherits the permissions from the parent. When disabling inheritance, the user is given the choice to convert inherited permissions to explicit permissions.

**Comment by jendib** [comment] 2022-03-20 19:22
Duplicate of #196
You can add your enabled/disabled toggle as comment over there.

**Closed by jendib** 2022-03-20 19:22 UTC
