### ISSUE TITLE
Feature request: Document rotation

### ISSUE THREAD

**Issue by GeorgeHahn** [sismics/docs#530] opened 2021-03-27 22:24 UTC
First I'd like to say thank you for building and sharing this tool!

One problem I'm running into is that many of my documents are upside-down or sideways, depending on how they were scanned. It would be helpful if docs supported rotating them automatically or manually.

**Comment by jendib** [comment] 2021-05-27 10:29
The documents are automatically rotated using Exif tags. Otherwise for general image processing it's duplicate of #276

**Closed by jendib** 2021-05-27 10:29 UTC
