### ISSUE TITLE
(Feature request) check for duplicate documents

### ISSUE THREAD

**Issue by fototeddy** [sismics/docs#515] opened 2021-01-31 17:13 UTC
today I scanned a whole bunch of documents(around 100). Each with my scanner app on my phone and mail every document to mai import Mailaccount.
The IMAP Import of the google mail account worked fine for that. 
But I made the mistake to mail some of the files double. well of course it was my mistake but maybe teedy could detect double entries, especially when the have the same attributes and files.

**Comment by jendib** [comment] 2021-05-27 10:32
Duplicate of #293

**Closed by jendib** 2021-05-27 10:32 UTC
