### ISSUE TITLE
Restraint user for uploading or add anything

### ISSUE THREAD

**Issue by Abulenger** [sismics/docs#643] opened 2022-07-05 07:46 UTC
The title isn't very talking but i would like to know (because i tried but didn't see any option for that) if we can make anything about a user Read Only?
Im trying to put a online documentation for a company but each user can add tags, add documents etc...
I know we can put a quota like 0 Mo so no doc is uploaded, but the user can still create tags.

Someone as something about this ?

Thanks in advance.

**Comment by vmario89** [comment] 2022-07-05 08:10
Hi. i created a similar issue once. See https://github.com/sismics/docs/issues/410

i made some SQL script stuff to have some helpers. You may have a look at 

- https://stadtfabrikanten.org/display/TEED/Auto-delete+guest+tags
- https://stadtfabrikanten.org/display/TEED/Auto-delete+guest+documents
- https://stadtfabrikanten.org/display/TEED/Auto-delete+guest+comments

**Comment by jendib** [comment] 2022-07-05 08:22
Closing this one as duplicate of #410

**Closed by jendib** 2022-07-05 08:22 UTC
