### ISSUE TITLE
Move files between documents

### ISSUE THREAD

**Issue by vikaskedia** [sismics/docs#330] opened 2019-06-07 03:10 UTC
One of the best open source DMS that I have seen. Congratulations!! once again.

In our organization we upload a lot of files and later organize them.

How can I move a file from one document to other.

Thanks and regards,

Vikas

**Comment by jendib** [comment] 2019-06-07 14:04
Duplicate of #279.
However for your use case, you can already use the "Quick Upload" area. Dump files here, and organize them later.

**Closed by jendib** 2019-06-07 14:04 UTC
