### ISSUE TITLE
File title not correct for pdf files at download

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#503] opened 2021-01-12 12:12 UTC
Hi,
when downloading files from sismics documents i recognized pdf files alsways get the title "document.pdf" instead their actual file name. But when downloading things like png or jpeg the files have the same name like the have in the document.
jpeg:
![grafik](https://user-images.githubusercontent.com/5631071/104312995-afdb0380-54d7-11eb-8b0f-7033aa2c4709.png)
![grafik](https://user-images.githubusercontent.com/5631071/104312976-a6ea3200-54d7-11eb-915b-7b4c9071fabb.png)

pdf:
![grafik](https://user-images.githubusercontent.com/5631071/104313078-cda86880-54d7-11eb-9f46-b784540843f1.png)
![grafik](https://user-images.githubusercontent.com/5631071/104313066-c84b1e00-54d7-11eb-86b1-0134b1c13139.png)
here it should ne named "1.pdf" instead "document.pdf"

**Comment by jendib** [comment] 2021-01-21 17:06
It seems to be a Firefox issue. I tried with Firefox Windows and I reproduced the problem, but with Chrome it works perfectly.
https://github.com/mozilla/pdf.js/issues/6396 seems to indicate that it was fixed in 2018 but apparently not.

**Closed by jendib** 2021-01-21 17:06 UTC
Labels: bug
